### ISSUE TITLE
constant Error

### ISSUE THREAD

**Issue by JoTec2002** [awesomemotive/wp-mail-logging#181]
Hello,

I'm running:
PHP version: 8.2.6
Wordpress version: 6.2.2
Language: de_DE
WP Mail Logging Version: 1.11.2

Since I upgraded to PHP Version 8.2.6 I get regulary the following error:
Ein Fehler vom Typ E_ERROR wurde in der Zeile 196 der Datei .../wp-content/plugins/wp-mail-logging/src/WPML_LifeCycle.php verursacht. Fehlermeldung: Uncaught TypeError: array_merge(): Argument #2 must be of type array, null given in .../wp-content/plugins/wp-mail-logging/src/WPML_LifeCycle.php:196
Stack trace:
#0 .../wp-content/plugins/wp-mail-logging/src/WPML_LifeCycle.php(196): array_merge(Array, NULL)
#1 .../wp-includes/class-wp-hook.php(308): No3x\WPML\WPML_LifeCycle->registerPluginActionLinks(NULL, 'wp-mail-logging...', NULL, 'all')
#2 .../wp-includes/plugin.php(205): WP_Hook->apply_filters(NULL, Array)
....

**Comment by donmhico** [comment]
Hello @JoTec2002,

Thanks for creating this issue. Can you try to deactivate other plugins on your site and see if the issue persists? The issue is for some reason `$actions` that was passed through this filter [plugin_action_links](https://developer.wordpress.org/reference/hooks/plugin_action_links/) is `NULL` instead of an expected array. We suspect that one of the other plugins activated on your site is causing this.

**Comment by JoTec2002** [comment]
Hey I have checked your theory and it seams, that Jetpack is causing the Problem.

Is there any way to fix the Problem without deaktivating Jetpack?

**Comment by donmhico** [comment]
@JoTec2002 - It'll be ideal if the issue is fixed in the plugin with the issue. Can you share the version of Jetpack you are using?

**Comment by JoTec2002** [comment]
I‘m currently using Version 12.3.
